# use the python image from the docker hub
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# copy the current dir contents into the container at /app
COPY . /app

# install the needed packages specified in the requirements.txt
RUN pip install flask

# make port 5000 available to the world outside this container
EXPOSE 5000

# run app.py when the container launches
CMD ["python", "app.py"]
